site_name: MLC Foundation
copyright: Copyright (C) 2020-22, MLC Foundation. All rights reserved.
theme:
  cluster

nav:
  - Home: index.md
  - Activities:
      - Studies: activities/studies.md
      - Seminars: activities/seminars.md
  - Research:
      - Publications: research/publications.md
      - NFHS: research/nfhs.md
      - FPPE: research/fppe.md
  - IJPD: ijpd.md
  - About:
      - Trustees: about/trustees.md
      - Experts: about/experts.md
      - Facilities: about/facilities.md
      - Contact: about/contact.md