site_name: MLC Foundation
copyright: Copyright (C) 2020-22, MLC Foundation. All rights reserved.
theme:
  windmill

nav:
  - Home: index.md
  - Activities:
      - Studies: activities/studies.md
      - Seminars: activities/seminars.md
  - Research:
      - Publications: research/publications.md
      - NFHS: research/nfhs.md
      - FPPE: research/fppe.md
  - IJPD:
      - Indian Journal of Population and Development: ijpd/journal.md
      - 'Editorial Board': ijpd/editors.md
      - 'Editorial Policy': ijpd/policy.md
      - Submissions: ijpd/submission.md
      - 'Current Issue': ijpd/issues.md
      - Archives: ijpd/archives.md
      - Contact: ijpd/contact.md
  - About:
      - Trustees: about/trustees.md
      - Experts: about/experts.md
      - Facilities: about/facilities.md
      - Contact: about/contact.md

extra:
  article_nav_top: False
  article_nav_bottom: False