name: "Deploy to GitHub pages"
on:
  [push, workflow_dispatch]:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - with:
          python-version: 3.x
      - run: pip install mkdocs-cluster
      - run: mkdocs gh-deploy --force
